### ISSUE TITLE
Updating table layout / columns breaks column toggling

### ISSUE THREAD

**Issue by tristaaan** [GwtMaterialDesign/gwt-material-table#210]
My solution to get around this was to simply not use the built-in row selection features if the column toggle menu is present or if columns were being added/removed depending on data.

![animation 11 59 48 AM](https://user-images.githubusercontent.com/5470619/119544499-c33c8c00-bd5f-11eb-941a-5fbbef033a10.gif)

**Comment by kevzlou7979** [comment]
This was addressed on GMD 2.5.0-SNAPSHOT

**Comment by kevzlou7979** [comment]
You can test it here and confirm if the issue still exist. https://gwtmaterialdesign.github.io/gmd-table-demo/snapshot/#standard

**Comment by tristaaan** [comment]
Still seeing it there too. Steps to reproduce: 

1. Remove a column / add a column
2. Add the column back / remove that added column
3. Toggle a column with the table menu
-> The toggled column will be off in some way. Here toggling the "First Name" column hides the image column but not the header

Steps 1 and 2 in the gif are done by changing the table selection type which adds or removes the checkbox column. Locally I've reproduced it independent of changing the selection type. 

![animation](https://user-images.githubusercontent.com/5470619/119997590-dfc60780-bf9d-11eb-9509-c31550452cf8.gif)
